### ISSUE TITLE
Meta tags

### ISSUE THREAD

**Issue by Abibubble** [Code-Institute-Community/business-analysis-project#46]
Meta tags are needed to ensure full SEO success for the site, including different meta tags for each page.

- [x] Add blocks to insert data into meta tags per page
- [x] Add base template meta tags
- [ ] Add images of pages to show on social media sharing
- [ ] Ensure canonical URLs are correct after we deploy
- [ ] Ensure relevant meta tags are different for each page
